# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8cd2e2b69fc6606ef2b0fdc535f1cd33d8973dd3834f48fa4bfe9f54d0f83d8b0b84097cac9ba079c7aa5560a5fce43572b94b26f5c103502940c52e890bf8b

test:
  secret_key_base: a8539ff1fcd19f21db0ee389afa54309a74d35f6a0a43b0fe4737d552d5406a0ecfcb24b916485db7bd003707ae2ca9907fedbc22167f1963fcab47dd40afce0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
